import { assertAuthorized, optionalEnv, requiredEnv } from '../../../lib/env';
import { supabaseAdmin, insertSessionLog } from '../../../lib/supabase';

const VERSION = 'repo-create-and-push-v1';

type GitHubRepo = {
  full_name: string;
  html_url: string;
  default_branch?: string;
};

function ghHeaders() {
  return {
    accept: 'application/vnd.github+json',
    authorization: `Bearer ${requiredEnv('GITHUB_TOKEN')}`,
    'content-type': 'application/json',
    'x-github-api-version': '2022-11-28'
  };
}

function safeRepoName(value: any) {
  return String(value || '')
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 90) || 'generated-repo';
}

function b64(content: string) {
  return Buffer.from(content || '', 'utf8').toString('base64');
}

async function gh(path: string, init: RequestInit = {}) {
  const res = await fetch(`https://api.github.com${path}`, { ...init, headers: { ...ghHeaders(), ...(init.headers || {}) } });
  const text = await res.text();
  let json: any = {};
  try { json = text ? JSON.parse(text) : {}; } catch { json = { raw: text }; }
  return { ok: res.ok, status: res.status, json };
}

async function getRepo(fullName: string) {
  const res = await gh(`/repos/${fullName}`);
  return res.ok ? res.json as GitHubRepo : null;
}

async function createRepo(owner: string, name: string, description: string) {
  const existing = await getRepo(`${owner}/${name}`);
  if (existing) return { repo: existing, created: false };

  const body = {
    name,
    description,
    private: false,
    has_issues: true,
    has_projects: false,
    has_wiki: false,
    auto_init: false
  };

  let res = await gh('/user/repos', { method: 'POST', body: JSON.stringify(body) });
  if (!res.ok && owner) {
    res = await gh(`/orgs/${owner}/repos`, { method: 'POST', body: JSON.stringify(body) });
  }
  if (!res.ok) throw new Error(`GitHub create repo failed ${res.status}: ${JSON.stringify(res.json)}`);
  return { repo: res.json as GitHubRepo, created: true };
}

async function putFile(fullName: string, path: string, content: string, message: string) {
  const res = await gh(`/repos/${fullName}/contents/${encodeURIComponent(path).replace(/%2F/g, '/')}`, {
    method: 'PUT',
    body: JSON.stringify({ message, content: b64(content), branch: 'main' })
  });
  if (!res.ok) throw new Error(`GitHub put file failed ${path} ${res.status}: ${JSON.stringify(res.json)}`);
  return res.json;
}

export async function GET(req: Request) { return run(req); }
export async function POST(req: Request) { return run(req); }

async function run(req: Request) {
  try {
    assertAuthorized(req);
    const supabase = supabaseAdmin();
    const url = new URL(req.url);
    const planId = url.searchParams.get('plan_id');
    const owner = optionalEnv('GITHUB_OWNER', '6eu6');

    let planQuery = supabase
      .from('repo_build_plans')
      .select('*')
      .eq('status', 'validated_ready')
      .order('readiness_score', { ascending: false })
      .limit(1);
    if (planId) planQuery = planQuery.eq('id', planId);
    const { data: plans, error: plansError } = await planQuery;
    if (plansError) throw plansError;
    if (!plans?.length) {
      return Response.json({ ok: true, version: VERSION, created: false, note: 'No validated_ready build plan found.' });
    }

    const plan = plans[0];
    const repoName = safeRepoName(plan.proposed_repo_name);
    const fullName = `${owner}/${repoName}`;

    const { data: existingOwned } = await supabase.from('owned_repo_projects').select('*').eq('github_full_name', fullName).maybeSingle();
    if (existingOwned) {
      return Response.json({ ok: true, version: VERSION, created: false, repo: existingOwned, note: 'Repo already registered in owned_repo_projects.' });
    }

    const { data: latestValidation } = await supabase
      .from('repo_validation_runs')
      .select('*')
      .eq('repo_build_plan_id', plan.id)
      .order('created_at', { ascending: false })
      .limit(1)
      .maybeSingle();
    if (!latestValidation || latestValidation.status !== 'passed') {
      return Response.json({ ok: false, version: VERSION, error: 'Latest validation is not passed. Run repo-validation-run first.' }, { status: 400 });
    }

    const { data: artifacts, error: artifactsError } = await supabase
      .from('repo_build_artifacts')
      .select('*')
      .eq('repo_build_plan_id', plan.id)
      .eq('quality_status', 'ready')
      .order('artifact_path', { ascending: true });
    if (artifactsError) throw artifactsError;
    if (!artifacts?.length) throw new Error('No ready artifacts found for plan.');

    const { repo, created } = await createRepo(owner, repoName, plan.repo_description || plan.v1_goal || 'Generated by X AI Content Factory Orchestrator');
    const pushed: any[] = [];
    for (const artifact of artifacts) {
      const path = String(artifact.artifact_path || '').trim();
      const content = String(artifact.generated_content || '');
      if (!path || !content) continue;
      const result = await putFile(repo.full_name, path, content, `Add ${path}`);
      pushed.push({ path, commit_sha: result?.commit?.sha || null });
    }

    const { data: owned, error: ownedError } = await supabase.from('owned_repo_projects').insert({
      repo_creation_decision_id: plan.repo_creation_decision_id || null,
      github_full_name: repo.full_name,
      repo_url: repo.html_url,
      repo_type: plan.repo_type_inferred || 'tool',
      status: 'active',
      build_status: 'pushed',
      test_status: 'pending_github_validation',
      maintenance_status: 'watching',
      supported_languages: ['en'],
      quality_report: { latest_validation_id: latestValidation.id, artifact_count: artifacts.length, pushed_count: pushed.length },
      content_links: [],
      investment_status: 'unproven',
      investment_score: 0,
      updated_at: new Date().toISOString()
    }).select('*').single();
    if (ownedError) throw ownedError;

    await supabase.from('repo_build_plans').update({ status: 'repo_created', updated_at: new Date().toISOString() }).eq('id', plan.id);
    await supabase.from('repo_validation_runs').update({ owned_repo_project_id: owned.id }).eq('id', latestValidation.id);

    const log = await insertSessionLog({
      actions_completed: ['repo_create_and_push', VERSION, repo.full_name, `files:${pushed.length}`],
      github_updates: [{ repo: repo.full_name, url: repo.html_url, created, pushed }],
      db_updates: [{ table: 'owned_repo_projects', id: owned.id }, { table: 'repo_build_plans', id: plan.id, status: 'repo_created' }],
      pending_tasks: ['Run repo post-push validation and create launch content for X.'],
      next_recommendation: 'Run repo-investment-run only after launch content and initial GitHub metrics exist.'
    });

    return Response.json({ ok: true, version: VERSION, created, repo: owned, github: repo, pushed, sessionLog: log });
  } catch (err: any) {
    return Response.json({ ok: false, version: VERSION, error: err.message }, { status: 500 });
  }
}
