import { assertAuthorized, optionalEnv } from '../../../lib/env';
import { supabaseAdmin, insertSessionLog } from '../../../lib/supabase';
import { getXUserByUsername } from '../../../lib/x';
import { generateDailyContentPack } from '../../../lib/content';
import { GROWTH_OPERATOR_VERSION, enrichGrowthOperatorPack } from '../../../lib/growth';

const ORCHESTRATOR_VERSION = `${GROWTH_OPERATOR_VERSION}+viral-memory`;

export async function POST(req: Request) { return run(req); }
export async function GET(req: Request) { return run(req); }

async function run(req: Request) {
  try {
    assertAuthorized(req);
    const supabase = supabaseAdmin();
    const username = optionalEnv('X_USERNAME', '30piq');

    let xSnapshot: any = null;
    try {
      xSnapshot = await getXUserByUsername(username);
      await supabase.from('account_state').upsert({
        account_handle: username,
        x_url: `https://x.com/${username}`,
        followers_count: xSnapshot.followers_count ?? null,
        following_count: xSnapshot.following_count ?? null,
        posts_count: xSnapshot.tweet_count ?? null,
        bio_text: xSnapshot.description ?? null,
        display_name: xSnapshot.name ?? null,
        profile_image_set: Boolean(xSnapshot?.profile_image_url),
        verified_status: xSnapshot.verified === undefined ? 'unknown' : String(xSnapshot.verified),
        last_live_check_at: new Date().toISOString(),
        last_known_source: 'daily_run_twitterapi'
      }, { onConflict: 'account_handle' });
    } catch (e: any) {
      xSnapshot = { warning: 'X live check failed or skipped', error: e.message };
    }

    const [accountState, requirements, targets, recentContent, creatorIntel, trends, viralRuns, viralTweets, viralPatterns] = await Promise.all([
      supabase.from('account_state').select('*').eq('account_handle', username).maybeSingle(),
      supabase.from('requirement_status').select('*').order('priority', { ascending: true }).limit(50),
      supabase.from('target_plans').select('*').eq('active', true).order('priority', { ascending: true }).limit(50),
      supabase.from('content_log').select('*').order('published_at', { ascending: false }).limit(30),
      supabase.from('creator_intel').select('*').order('created_at', { ascending: false }).limit(20),
      supabase.from('trends').select('*').eq('covered', false).order('heat_score', { ascending: false }).limit(20),
      supabase.from('viral_scan_runs').select('*').order('created_at', { ascending: false }).limit(10),
      supabase.from('viral_tweet_analyses').select('*').order('engagement_per_1k_followers', { ascending: false }).limit(30),
      supabase.from('viral_account_patterns').select('*').order('confidence_score', { ascending: false }).order('created_at', { ascending: false }).limit(30)
    ]);

    const viralMemory = {
      recent_scan_runs: viralRuns.data || [],
      high_performing_tweet_analyses: viralTweets.data || [],
      high_confidence_patterns: viralPatterns.data || [],
      usage_rule: 'Use viral memory as mechanics only. Do not copy creator wording, claims, or examples.'
    };

    const rawContentPack = await generateDailyContentPack({
      accountState: { db: accountState.data, xSnapshot },
      targets: targets.data,
      requirements: requirements.data,
      recentContent: recentContent.data,
      creatorIntel: { creator_intel: creatorIntel.data, trends: trends.data, viral_memory: viralMemory }
    });
    const contentPack = enrichGrowthOperatorPack(rawContentPack);

    const singleTweets = Array.isArray(contentPack.single_tweets) ? contentPack.single_tweets : [];
    const replies = Array.isArray(contentPack.reply_targets_strategy) ? contentPack.reply_targets_strategy : [];
    const quotes = Array.isArray(contentPack.quote_tweet_strategy) ? contentPack.quote_tweet_strategy : [];

    const { data: runRow, error: runError } = await supabase.from('daily_checkins').upsert({
      checkin_date: new Date().toISOString().slice(0, 10),
      execution_mode: contentPack.mode || 'partial',
      account_checked: Boolean(xSnapshot),
      account_check_source: xSnapshot?.warning ? 'skipped_or_failed' : 'twitterapi',
      profile_requirements_checked: true,
      daily_targets_checked: true,
      weekly_targets_checked: true,
      content_pack_created: true,
      tweets_planned: singleTweets.length,
      replies_planned: replies.length,
      quotes_planned: quotes.length,
      research_items_reviewed: Array.isArray(trends.data) ? trends.data.length : 0,
      creator_posts_analyzed: (Array.isArray(creatorIntel.data) ? creatorIntel.data.length : 0) + (Array.isArray(viralTweets.data) ? viralTweets.data.length : 0),
      github_assets_created: contentPack.github_decision?.needed ? 1 : 0,
      next_priority: contentPack.today_goal || 'Publish prepared content and log URLs.',
      notes: `Generated by daily-run API ${ORCHESTRATOR_VERSION}. Viral patterns used: ${(viralPatterns.data || []).length}. Viral tweets used: ${(viralTweets.data || []).length}.`
    }, { onConflict: 'checkin_date' }).select('*').single();
    if (runError) throw runError;

    if (singleTweets.length) {
      const { error: contentError } = await supabase.from('content_log').insert(singleTweets.map((t: any) => ({
        content_type: 'single_tweet',
        topic: contentPack.today_goal || 'AI productivity career growth',
        hook_text: t.text?.slice(0, 240) || null,
        final_text: t.text || null,
        target_audience: 'English-speaking AI productivity career growth audience',
        originality_element: t.originality_element || t.why_this_is_not_generic || 'Original safe angle',
        source_used: ORCHESTRATOR_VERSION,
        publish_status: 'ready',
        notes: JSON.stringify({
          why_it_works: t.why_it_works || null,
          mechanic_used: t.mechanic_used || null,
          viral_pattern_basis: t.viral_pattern_basis || null,
          reply_trigger: t.reply_trigger || null,
          bookmark_trigger: t.bookmark_trigger || null
        })
      })));
      if (contentError) throw contentError;
    }

    const actions = Array.isArray(contentPack.next_actions) ? contentPack.next_actions : [];
    if (actions.length) {
      await supabase.from('action_queue').insert(actions.map((instruction: string, index: number) => ({
        priority: index + 1,
        action_type: 'human_publish_or_engage',
        title: `Growth daily action ${index + 1}`,
        instruction,
        prepared_content: JSON.stringify(contentPack),
        status: 'pending',
        assigned_to: 'human_operator'
      })));
    }

    const { data: pendingActions } = await supabase
      .from('action_queue')
      .select('id,priority,action_type,title,instruction,status,assigned_to,created_at')
      .eq('status', 'pending')
      .ilike('title', 'Growth daily action%')
      .order('created_at', { ascending: false })
      .order('priority', { ascending: true })
      .limit(7);

    const sessionLog = await insertSessionLog({
      actions_completed: ['daily_run', ORCHESTRATOR_VERSION, 'x_check_attempted', 'used_research_intel', 'used_viral_memory', 'generated_growth_operator_pack', 'updated_daily_checkin'],
      content_created: singleTweets,
      db_updates: [{ table: 'daily_checkins', id: runRow.id }, { table: 'content_log', rows: singleTweets.length }],
      pending_tasks: actions,
      next_recommendation: 'Publish approved items manually, then log URLs and metrics so weekly review can compare output against viral mechanics.'
    });

    return Response.json({
      ok: true,
      orchestrator_version: ORCHESTRATOR_VERSION,
      xSnapshot,
      research_context: { trends: trends.data, creator_intel: creatorIntel.data, viral_memory: viralMemory },
      contentPack,
      daily_checkin: runRow,
      sessionLog,
      pendingActions: pendingActions || []
    });
  } catch (err: any) {
    return Response.json({ ok: false, orchestrator_version: ORCHESTRATOR_VERSION, error: err.message }, { status: 500 });
  }
}
